-- Wyckoff-Analysis Supabase schema
-- Generated from project code paths in:
--   core/constants.py
--   integrations/supabase_client.py
--   integrations/supabase_portfolio.py
--   integrations/supabase_recommendation.py
--   integrations/supabase_market_signal.py
--   integrations/download_history.py
--   core/stock_cache.py
--
-- Run this in Supabase SQL Editor.
-- This script creates:
--   1) application tables
--   2) indexes / constraints
--   3) RLS policies
--   4) optional storage bucket for download history

begin;

create schema if not exists public;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =========================================================
-- 1. User settings
-- =========================================================

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,

  feishu_webhook text,
  wecom_webhook text,
  dingtalk_webhook text,

  gemini_api_key text,
  gemini_model text,
  gemini_base_url text,

  openai_api_key text,
  openai_model text,
  openai_base_url text,

  deepseek_api_key text,
  deepseek_model text,
  deepseek_base_url text,

  -- compatibility / legacy flat provider fields
  zhipu_api_key text,
  zhipu_model text,
  zhipu_base_url text,
  minimax_api_key text,
  minimax_model text,
  minimax_base_url text,
  qwen_api_key text,
  qwen_model text,
  qwen_base_url text,
  kimi_api_key text,
  kimi_model text,
  kimi_base_url text,
  volcengine_api_key text,
  volcengine_model text,
  volcengine_base_url text,

  custom_providers jsonb not null default '{}'::jsonb,
  tushare_token text,
  tg_bot_token text,
  tg_chat_id text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_user_settings_updated_at on public.user_settings;
create trigger trg_user_settings_updated_at
before update on public.user_settings
for each row execute function public.set_updated_at();

-- =========================================================
-- 2. Download history
-- =========================================================

create table if not exists public.download_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  page text not null,
  source text not null,
  title text not null,
  file_name text not null,
  mime text,
  size_kb numeric(12, 1) not null default 0,
  artifact_bucket text,
  artifact_path text,
  request_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_download_history_user_created
  on public.download_history (user_id, created_at desc);

-- =========================================================
-- 3. Portfolio domain
-- =========================================================

create table if not exists public.portfolios (
  portfolio_id text primary key,
  name text not null default '',
  free_cash numeric(18, 2) not null default 0,
  total_equity numeric(18, 2),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_portfolios_updated_at on public.portfolios;
create trigger trg_portfolios_updated_at
before update on public.portfolios
for each row execute function public.set_updated_at();

create table if not exists public.portfolio_positions (
  portfolio_id text not null references public.portfolios(portfolio_id) on delete cascade,
  code text not null check (code ~ '^[0-9]{6}$'),
  name text not null default '',
  shares integer not null default 0,
  cost_price numeric(18, 4) not null default 0,
  buy_dt text,
  strategy text,
  stop_loss numeric(18, 4),
  updated_at timestamptz not null default now(),
  primary key (portfolio_id, code)
);

create index if not exists idx_portfolio_positions_portfolio
  on public.portfolio_positions (portfolio_id);

drop trigger if exists trg_portfolio_positions_updated_at on public.portfolio_positions;
create trigger trg_portfolio_positions_updated_at
before update on public.portfolio_positions
for each row execute function public.set_updated_at();

create table if not exists public.trade_orders (
  id bigint generated by default as identity primary key,
  run_id text not null,
  portfolio_id text not null references public.portfolios(portfolio_id) on delete cascade,
  trade_date date not null,
  model text,
  market_view text,
  code text not null check (code ~ '^[0-9]{6}$'),
  name text,
  action text,
  status text,
  shares integer not null default 0,
  price_hint numeric(18, 4),
  amount numeric(18, 2) not null default 0,
  stop_loss numeric(18, 4),
  max_loss numeric(18, 2) not null default 0,
  drawdown_ratio numeric(12, 6) not null default 0,
  reason text,
  tape_condition text,
  invalidate_condition text,
  created_at timestamptz not null default now()
);

create index if not exists idx_trade_orders_portfolio_trade_date
  on public.trade_orders (portfolio_id, trade_date, created_at desc);

create index if not exists idx_trade_orders_run_id
  on public.trade_orders (run_id);

create table if not exists public.daily_nav (
  portfolio_id text not null references public.portfolios(portfolio_id) on delete cascade,
  trade_date date not null,
  free_cash numeric(18, 2) not null default 0,
  positions_value numeric(18, 2) not null default 0,
  total_equity numeric(18, 2) not null default 0,
  updated_at timestamptz not null default now(),
  primary key (portfolio_id, trade_date)
);

create index if not exists idx_daily_nav_portfolio_date
  on public.daily_nav (portfolio_id, trade_date desc);

drop trigger if exists trg_daily_nav_updated_at on public.daily_nav;
create trigger trg_daily_nav_updated_at
before update on public.daily_nav
for each row execute function public.set_updated_at();

-- =========================================================
-- 4. Shared data tables
-- =========================================================

create table if not exists public.recommendation_tracking (
  id bigint generated by default as identity primary key,
  code integer not null,
  name text,
  recommend_reason text,
  recommend_date integer not null,
  initial_price numeric(18, 4) not null default 0,
  current_price numeric(18, 4) not null default 0,
  change_pct numeric(12, 2) not null default 0,
  recommend_count integer not null default 1,
  funnel_score numeric(18, 6),
  is_ai_recommended boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_recommendation_tracking_code_date unique (code, recommend_date)
);

create index if not exists idx_recommendation_tracking_date
  on public.recommendation_tracking (recommend_date desc);

create index if not exists idx_recommendation_tracking_code
  on public.recommendation_tracking (code);

create index if not exists idx_recommendation_tracking_ai
  on public.recommendation_tracking (is_ai_recommended, recommend_date desc);

drop trigger if exists trg_recommendation_tracking_updated_at on public.recommendation_tracking;
create trigger trg_recommendation_tracking_updated_at
before update on public.recommendation_tracking
for each row execute function public.set_updated_at();

create table if not exists public.market_signal_daily (
  trade_date date primary key,

  benchmark_regime text,
  main_index_code text,
  main_index_close numeric(18, 4),
  main_index_ma50 numeric(18, 4),
  main_index_ma200 numeric(18, 4),
  main_index_recent3_cum_pct numeric(12, 4),
  main_index_today_pct numeric(12, 4),

  smallcap_index_code text,
  smallcap_close numeric(18, 4),
  smallcap_recent3_cum_pct numeric(12, 4),

  a50_value_date date,
  a50_source text,
  a50_close numeric(18, 4),
  a50_pct_chg numeric(12, 4),

  vix_value_date date,
  vix_source text,
  vix_close numeric(18, 4),
  vix_pct_chg numeric(12, 4),

  premarket_regime text,
  premarket_reasons jsonb not null default '[]'::jsonb,
  source_jobs jsonb not null default '{}'::jsonb,

  benchmark_slot text,
  premarket_slot text,
  market_posture_code text,
  market_posture_name text,
  wind_phrase text,
  water_phrase text,
  action_phrase text,
  banner_tone text,
  banner_title text,
  banner_message text,

  updated_at timestamptz not null default now()
);

drop trigger if exists trg_market_signal_daily_updated_at on public.market_signal_daily;
create trigger trg_market_signal_daily_updated_at
before update on public.market_signal_daily
for each row execute function public.set_updated_at();

create table if not exists public.stock_hist_cache (
  symbol text not null,
  adjust text not null,
  date date not null,
  open numeric(18, 4),
  high numeric(18, 4),
  low numeric(18, 4),
  close numeric(18, 4),
  volume numeric(24, 4),
  amount numeric(24, 4),
  pct_chg numeric(12, 4),
  updated_at timestamptz not null default now(),
  primary key (symbol, adjust, date)
);

create index if not exists idx_stock_hist_cache_symbol_adjust_date
  on public.stock_hist_cache (symbol, adjust, date desc);

drop trigger if exists trg_stock_hist_cache_updated_at on public.stock_hist_cache;
create trigger trg_stock_hist_cache_updated_at
before update on public.stock_hist_cache
for each row execute function public.set_updated_at();

-- =========================================================
-- 5. Grants
-- =========================================================

grant usage on schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

grant select on public.market_signal_daily to anon, authenticated;
grant select on public.recommendation_tracking to anon, authenticated;
grant select on public.stock_hist_cache to anon, authenticated;

grant insert, update, delete on public.stock_hist_cache to authenticated;

grant select, insert, update, delete on public.user_settings to authenticated;
grant select, insert, update, delete on public.download_history to authenticated;
grant select, insert, update, delete on public.portfolios to authenticated;
grant select, insert, update, delete on public.portfolio_positions to authenticated;
grant select, insert, update, delete on public.trade_orders to authenticated;
grant select, insert, update, delete on public.daily_nav to authenticated;

-- =========================================================
-- 6. RLS for user-owned tables
-- =========================================================

alter table public.user_settings enable row level security;
alter table public.download_history enable row level security;
alter table public.portfolios enable row level security;
alter table public.portfolio_positions enable row level security;
alter table public.trade_orders enable row level security;
alter table public.daily_nav enable row level security;
alter table public.recommendation_tracking disable row level security;
alter table public.market_signal_daily disable row level security;
alter table public.stock_hist_cache disable row level security;

drop policy if exists user_settings_owner_all on public.user_settings;
create policy user_settings_owner_all
on public.user_settings
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists download_history_owner_all on public.download_history;
create policy download_history_owner_all
on public.download_history
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists portfolios_owner_all on public.portfolios;
create policy portfolios_owner_all
on public.portfolios
for all
to authenticated
using (portfolio_id = ('USER_LIVE:' || auth.uid()::text))
with check (portfolio_id = ('USER_LIVE:' || auth.uid()::text));

drop policy if exists portfolio_positions_owner_all on public.portfolio_positions;
create policy portfolio_positions_owner_all
on public.portfolio_positions
for all
to authenticated
using (portfolio_id = ('USER_LIVE:' || auth.uid()::text))
with check (portfolio_id = ('USER_LIVE:' || auth.uid()::text));

drop policy if exists trade_orders_owner_all on public.trade_orders;
create policy trade_orders_owner_all
on public.trade_orders
for all
to authenticated
using (portfolio_id = ('USER_LIVE:' || auth.uid()::text))
with check (portfolio_id = ('USER_LIVE:' || auth.uid()::text));

drop policy if exists daily_nav_owner_all on public.daily_nav;
create policy daily_nav_owner_all
on public.daily_nav
for all
to authenticated
using (portfolio_id = ('USER_LIVE:' || auth.uid()::text))
with check (portfolio_id = ('USER_LIVE:' || auth.uid()::text));

-- Shared tables are intentionally left without RLS here.
-- Writes are expected from service role / backend jobs,
-- except stock_hist_cache which can also be written by authenticated users.

-- =========================================================
-- 7. Optional storage bucket for download_history
-- =========================================================

insert into storage.buckets (id, name, public)
values ('download-history', 'download-history', false)
on conflict (id) do nothing;

drop policy if exists download_history_bucket_select_own on storage.objects;
create policy download_history_bucket_select_own
on storage.objects
for select
to authenticated
using (
  bucket_id = 'download-history'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists download_history_bucket_insert_own on storage.objects;
create policy download_history_bucket_insert_own
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'download-history'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists download_history_bucket_update_own on storage.objects;
create policy download_history_bucket_update_own
on storage.objects
for update
to authenticated
using (
  bucket_id = 'download-history'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'download-history'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists download_history_bucket_delete_own on storage.objects;
create policy download_history_bucket_delete_own
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'download-history'
  and (storage.foldername(name))[1] = auth.uid()::text
);

commit;
